<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        
        DB::table('menus')->insert([
            [
                'nama' => 'Nasi Goreng Spesial',
                'harga' => 18000.00,
                'deskripsi' => 'Nasi goreng dengan telur, ayam, dan kerupuk',
                'gambar' => 'nasi-goreng.jpg',
                'tenant_id' => 1, // Sesuaikan dengan tenant ID yang ada
                'category_id' => 1, // Standardized to category_id
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Mie Ayam Bakso',
                'harga' => 15000.00,
                'deskripsi' => 'Mie ayam lengkap dengan bakso dan sayur segar',
                'gambar' => 'mie-ayam-bakso.jpg',
                'tenant_id' => 1,
                'category_id' => 1, // Standardized to category_id
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Es Teh Manis',
                'harga' => 5000.00,
                'deskripsi' => 'Minuman es teh manis segar',
                'gambar' => 'es-teh-manis.jpg',
                'tenant_id' => 1,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Ayam Geprek Level 3',
                'harga' => 20000.00,
                'deskripsi' => 'Ayam geprek pedas level 3 dengan nasi dan lalapan',
                'gambar' => 'ayam-geprek.jpg',
                'tenant_id' => 2, // Tenant lain
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Sate Ayam Lontong',
                'harga' => 22000.00,
                'deskripsi' => 'Sate ayam dengan lontong dan bumbu kacang',
                'gambar' => 'sate-ayam.jpg',
                'tenant_id' => 2,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Shi Katsu',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi, chicken katsu, salad dengan pilihan saus: barbeque, lada hitam, atau spicy fire ricis',
                'gambar' => 'shi-katsu.jpg',
                'tenant_id' => 11,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Hokyben',
                'harga' => 16000.00,
                'deskripsi' => 'Nasi, ayam katsu, tori chicken, shrimp ball, dan salad',
                'gambar' => 'hokyben.jpg',
                'tenant_id' => 11,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Katsu',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi goreng dengan chicken katsu',
                'gambar' => 'nasi-goreng-katsu.jpg',
                'tenant_id' => 11,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Telur',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi goreng dengan telur ceplok',
                'gambar' => 'nasi-goreng-telur.jpg',
                'tenant_id' => 11,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Bisteak Ayam',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi, ayam filet bistik dengan pilihan saus: barbeque, lada hitam, spicy fire ricis',
                'gambar' => 'nasi-bisteak-ayam.jpg',
                'tenant_id' => 11,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Bisteak Ayam Geprek',
                'harga' => 14000.00,
                'deskripsi' => 'Nasi, ayam filet bistik dan sambal geprek',
                'gambar' => 'nasi-bisteak-geprek.jpg',
                'tenant_id' => 11,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Steak Ayam',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi dan ayam steak dengan saus: lada hitam, teriyaki, atau barbeque',
                'gambar' => 'nasi-steak-ayam.jpg',
                'tenant_id' => 11,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Es Teh Manis',
                'harga' => 5000.00,
                'deskripsi' => 'Minuman es teh manis segar',
                'gambar' => 'es-teh-manis.jpg',
                'tenant_id' => 11,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Manggo Jelly',
                'harga' => 8000.00,
                'deskripsi' => 'Minuman mangga dengan jelly',
                'gambar' => 'manggo-jelly.jpg',
                'tenant_id' => 11,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Avocado Jelly',
                'harga' => 8000.00,
                'deskripsi' => 'Minuman alpukat dengan jelly',
                'gambar' => 'avocado-jelly.jpg',
                'tenant_id' => 11,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Coklat Slurpy',
                'harga' => 8000.00,
                'deskripsi' => 'Minuman coklat dingin slurpy',
                'gambar' => 'coklat-slurpy.jpg',
                'tenant_id' => 11,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Cappucino Cincau',
                'harga' => 8000.00,
                'deskripsi' => 'Minuman cappucino dengan cincau',
                'gambar' => 'cappucino-cincau.jpg',
                'tenant_id' => 11,
                'category_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Special',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi goreng spesial dengan topping lengkap',
                'gambar' => 'nasi-goreng-special.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Ati Ampela',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi goreng dengan ati ampela',
                'gambar' => 'nasi-goreng-ati-ampela.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Mawut',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi goreng campur mie',
                'gambar' => 'nasi-goreng-mawut.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Oriental',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi goreng bumbu oriental khas',
                'gambar' => 'nasi-goreng-oriental.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Ayam Sosis',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi goreng dengan ayam dan sosis',
                'gambar' => 'nasi-goreng-ayam-sosis.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Katsu',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi goreng dengan chicken katsu',
                'gambar' => 'nasi-goreng-katsu.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Filet Geprek',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi goreng dengan filet ayam geprek',
                'gambar' => 'nasi-goreng-filet-geprek.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Goreng Ayam Geprek',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi goreng dengan ayam geprek',
                'gambar' => 'nasi-goreng-ayam-geprek.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Orak Arik',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi dengan telur orak arik',
                'gambar' => 'nasi-orak-arik.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Omlet',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi dengan telur omlet',
                'gambar' => 'nasi-omlet.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Sate Kukus',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi dengan sate kukus khas',
                'gambar' => 'nasi-sate-kukus.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Ayam Bakar',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi dengan ayam bakar',
                'gambar' => 'nasi-ayam-bakar.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Bakar Ayam',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi bakar isi ayam',
                'gambar' => 'nasi-bakar-ayam.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Cap Cay Goreng/Kuah',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi dengan cap cay goreng atau kuah',
                'gambar' => 'nasi-capcay.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Ayam Geprek',
                'harga' => 15000.00,
                'deskripsi' => 'Nasi dengan ayam geprek pedas',
                'gambar' => 'nasi-ayam-geprek.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Filet Geprek',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi dengan ayam filet geprek',
                'gambar' => 'nasi-filet-geprek.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Chiken Katsu',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi dengan chicken katsu',
                'gambar' => 'nasi-chiken-katsu.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama' => 'Nasi Chiken Grill',
                'harga' => 13000.00,
                'deskripsi' => 'Nasi dengan chicken grill',
                'gambar' => 'nasi-chiken-grill.jpg',
                'tenant_id' => 12,
                'category_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}